# Generated by Django 2.1.5 on 2019-02-04 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('emp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('dept', models.CharField(max_length=50)),
                ('ques_1_id', models.IntegerField()),
                ('ans_1', models.CharField(max_length=50)),
                ('ques_2_id', models.IntegerField()),
                ('ans_2', models.CharField(max_length=50)),
            ],
        ),
    ]
