# Generated by Django 2.1.5 on 2019-02-09 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_auto_20190208_1932'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('temp_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
