# Generated by Django 2.1.5 on 2019-02-09 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='password',
            field=models.CharField(help_text='Minimum of 8 Characters', max_length=50),
        ),
    ]
