# Generated by Django 2.1.5 on 2019-02-11 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_auto_20190212_0055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='dateTime',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
