# Generated by Django 2.1.5 on 2019-02-11 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0012_auto_20190212_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='dateTime',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
